name: "Podcast Generator"
author: "Me"
description: "Generates a feed for a podcast from a YAML"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "git-branch"
  color: "black"
inputs:
  email:
    description: Commiter's email
    required: true
    default: ${{ github.actor }}@localhost
  name:
    description: Commiter's name
    required: true
    default: ${{ github.actor }}